[package]
name = "vhost-device-gpu"
version = "0.1.0"
authors = ["Dorinda Bassey <dbassey@redhat.com>", "Matej Hrica <mhrica@redhat.com>"]
description = "A virtio-gpu device using the vhost-user protocol."
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["gpu", "vhost", "vhost-user", "virtio"]
categories = ["multimedia::video", "virtualization"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"
publish = false

[features]
xen = ["vm-memory/xen", "vhost/xen", "vhost-user-backend/xen"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11.5"
libc = "0.2"
log = "0.4"

[target.'cfg(not(target_env = "musl"))'.dependencies]
rutabaga_gfx = { version = "0.1.4", features = ["gfxstream", "virgl_renderer"] }
thiserror = "2.0.3"
vhost = { version = "0.13.0", features = ["vhost-user-backend"] }
vhost-user-backend = "0.17"
virtio-bindings = "0.2.2"
virtio-queue = "0.14.0"
vm-memory = "0.16.1"
vmm-sys-util = "0.12.1"

[dev-dependencies]
assert_matches = "1.5"
tempfile = "3.13"
virtio-queue = { version = "0.14", features = ["test-utils"] }
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-atomic"] }
mockall = "0.13.0"
rusty-fork = "0.3.0"