version: 2
updates:
- package-ecosystem: cargo
  directories:
    - "/"
    - "/staging/"
  schedule:
    interval: weekly
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  groups:
      rust-vmm:
        patterns:
          - "vhost"
          - "vhost-user-backend"
          - "virtio-bindings"
          - "virtio-queue"
          - "virtio-vsock"
          - "vm-memory"
          - "vmm-sys-util"
      non-rust-vmm:
        applies-to: security-updates
        patterns:
          - "*"
        exclude-patterns:
          - "vhost"
          - "vhost-user-backend"
          - "virtio-bindings"
          - "virtio-queue"
          - "virtio-vsock"
          - "vm-memory"
          - "vmm-sys-util"
- package-ecosystem: cargo
  directories:
    - "/"
    - "/staging/"
  schedule:
    interval: monthly
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  groups:
      vhost-device:
        patterns:
          - "*"
  # Makes it possible to have another config for the same directory.
  # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
  target-branch: main

- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
