[package]
name = "gpio"
version = "0.1.0"
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libgpiod = { git = "https://github.com/vireshk/libgpiod" }
