[package]
name = "vhost-device-gpio"
version = "0.1.0"
authors = ["Viresh Kumar <viresh.kumar@linaro.org>"]
description = "vhost gpio backend device"
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["gpio", "vhost", "virt", "backend"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2",  features = ["yaml"] }
env_logger = ">=0.9"
libc = ">=0.2.95"
libgpiod = { git = "https://github.com/vireshk/libgpiod" }
log = ">=0.4.6"
thiserror = "1.0"
vhost = { version = "0.2", features = ["vhost-user-slave"] }
vhost-user-backend = { git = "https://github.com/rust-vmm/vhost-user-backend", rev = "4047c697470cc6c37e8e1835025b091d2b59c2f7" }
virtio-bindings = ">=0.1"
virtio-queue = { git = "https://github.com/rust-vmm/vm-virtio", rev = "66cda80" }
vm-memory = "0.7"
vmm-sys-util = "=0.9.0"
