[package]
name = "vhost-device-can"
version = "0.1.0"
authors = ["Timos Ampelikiotis <t.ampelikiotis@virtualopensystems.com>"]
description = "vhost can backend device"
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["can", "vhost", "virt", "backend"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
xen = ["vm-memory/xen", "vhost/xen", "vhost-user-backend/xen"]

[dependencies]
clap = { version = "4.5",  features = ["derive"] }
env_logger = "0.11"
log = "0.4"
thiserror = "1.0"
queues = "1.0.2"
# TODO: Update socketcan to version "v3.4.0" when this is released.
# Socketcan "v3.3.0" includes the following issue: https://github.com/socketcan-rs/socketcan-rs/pull/61.
# The version was set to the commit "f004ee91e142a" where that issue has been resolved. As soon as, a
# newer version is released we need to point socketcan dependency to it.
# NOTE: If you are using rust version "1.80", the compiler might complain about "std::mem::size_of".
# The solution to that problem is described in the following link:
# - https://github.com/socketcan-rs/socketcan-rs/pull/72
socketcan = { git = "https://github.com/socketcan-rs/socketcan-rs.git", rev = "f004ee91e142a37fea36c5d719a57852c7076e87" }
vhost = { version = "0.13", features = ["vhost-user-backend"] }
vhost-user-backend = { version = "0.17" }
virtio-bindings = "0.2.2"
virtio-queue = "0.14"
vm-memory = "0.16.0"
vmm-sys-util = "0.12"

[dev-dependencies]
assert_matches = "1.5"
virtio-queue = { version = "0.14", features = ["test-utils"] }
vm-memory = { version = "0.16.0", features = ["backend-mmap", "backend-atomic"] }
